CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Ads" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(100) NOT NULL,
    "Price" integer NOT NULL,
    "Description" character varying(1000) NULL,
    "ImageUri" character varying(1000) NULL,
    "ThumbnailUri" character varying(1000) NULL,
    "PostedDate" timestamp with time zone NOT NULL,
    "Category" integer NOT NULL,
    "Phone" text NOT NULL,
    CONSTRAINT "PK_Ads" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220119213855_Initial', '6.0.2');

COMMIT;

